name: Reza Jatnika
title: Reza Jatnika
url: http://reza.re
description: ruby sandwich.rb

permalink: /blog/:year/:month/:day/:title/
paginate: 5
pygments: true
destination: public
timezone: Asia/Jakarta

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
